### ISSUE TITLE
Call to IOUtils.closeQuietly with passed in tag not being recognised

### ISSUE THREAD

**Issue by parky128** [devnied/EMV-NFC-Paycard-Enrollment#15]
In HomeActivity.java of the sample app, there is a try\catch block when reading the card

					} finally {
						// close tagcomm
						IOUtils.closeQuietly(mTagcomm);
					}
I'm getting a build issue on the the call to `closeQuietly` where there is no overload that takes an isodep tag param, the other overloads such as taking a stream param are present. Where does this isodep overload come from?

**Comment by devnied** [comment]
An IsoDep implements the Closeable Interface so I use closeQuietly(Closeable closeable) form Apache CommonsIO.
https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/IOUtils.html
