### ISSUE TITLE
Unknown EMV card Error

### ISSUE THREAD

**Issue by Chandrakala14** [devnied/EMV-NFC-Paycard-Enrollment#30]
Hi devnied,
Awesome Work...

My cards are reading from play store app, but when I used libs and smaple code provided by you getting **Unknown EMV Card error**.

Kindly help me to fix this issue.
Thank you for nice app.

**Comment by Chandrakala14** [comment]
Solved Error by changing NFC TAG AS

Tech [android.nfc.tech.IsoDep, android.nfc.tech.NfcA, android.nfc.tech.NdefFormatable]

**Comment by anna64000** [comment]
sorry

**Comment by ornolisvt** [comment]
In my case I had to add [android.nfc.tech.IsoDep, android.nfc.tech.NfcA, android.nfc.tech.NfcA, android.nfc.tech.MifareClassic, android.nfc.tech.NdefFormatable]
