### ISSUE TITLE
NFC on Sony Xperia S with this app physically destroyed two my MCs

### ISSUE THREAD

**Issue by brozkeff** [devnied/EMV-NFC-Paycard-Enrollment#34]
I used an older Sony Xperia S phone with a custom ROM of Android 7.1 (the only phone I have with NFC capability) and Credit Card Reader NFC (EMV) app to read the transaction history of my cards. It worked somehow but after a few attempts the NFC apparently PDoSed (bricked, toasted) two of my MasterCards issued by two different banks. NFC (PayPass contactless) functionality become dead and unresponsive completely as if the card never had contactless feature, and paying at the shop or withdrawing money at the ATM by chip produced also an error of unrecognized / faulty card. 

Some payment terminals at the shop displayed an error when trying to pay with the chip "error fallback use magnet stripe" but trying to use the magnet resulted in a loop-error "use chip instead", probably due to the fact that if both the card and the terminal supports chip it is mandated to NOT use the magnet, for security reasons perhaps.

One of the banks replaced me the card for free, but the second one wanted me to pay for the replacement card. I wonder how can a regular NFC in a phone induce such a dangerous fields that it can physically destroy the cards it is designed to regularly read!

**Comment by kr0no** [comment]
Could you say what custom rom are you using on your Sony Xperia?

**Comment by devnied** [comment]
That strange, because the library only used commands available in [EMV specification](https://www.emvco.com/).
What is your custom ROM ?

**Comment by brozkeff** [comment]
nAOSP 7.1.2 
https://forum.xda-developers.com/xperia-s/s-development/rom-naosprom-xperia-s-t3462373
