### ISSUE TITLE
Android 8.1.0 Update getting tag was lost exception

### ISSUE THREAD

**Issue by itsvicsoto** [devnied/EMV-NFC-Paycard-Enrollment#38]
Anybody having similar issues?

Android OS : 8.1.0

Getting this exception `com.github.devnied.emvnfccard.exception.CommunicationException: Tag was lost.` all the time after updating my android OS.

**Comment by HelloWorld-L** [comment]
same issues with Android 7.1

**Comment by TarasOryshhij** [comment]
any updates? also receive this error
