### ISSUE TITLE
cardholder name showing null

### ISSUE THREAD

**Issue by vajjasivateja** [devnied/EMV-NFC-Paycard-Enrollment#40]
Hi devnied,

I can able to get type of card, card issuer name, expiry date and card number but not card holder name and its showing null?

Help me with this.
Thanks

**Comment by SezerDilber** [comment]
According the scheme rules cardholder names are removed from Track 1 data. You may find some old or non compliant contactless cards which may still have cardholder name but any latest certified card should have blank on this field.

**Comment by rozzalia** [comment]
Some good dumps to Get somewere

tir. 19. feb. 2019 kl. 01:37 skrev Julien Millau <notifications@github.com>:

**Comment by humble-beast** [comment]
Are you in need of dumps my friend? 👀

**Comment by rozzalia** [comment]
Yes i am.  Depend on quality and how much IT is om the card
Iff u send quality and god dumps i wil rock. Live in norway and realy need
some good ones.

Price sir you have some good mobile apk ore know how make the nfc signal
stronger from a phone i also need machines and software

Icq.  746862209

tir. 19. feb. 2019 kl. 13:45 skrev humble-beast <notifications@github.com>:

**Comment by rozzalia** [comment]
Yes pleas
I need dumps

tir. 19. feb. 2019 kl. 13:45 skrev humble-beast <notifications@github.com>:

**Comment by rozzalia** [comment]
tir. 19. feb. 2019 kl. 13:45 skrev humble-beast <notifications@github.com>:
