### ISSUE TITLE
Pro Version

### ISSUE THREAD

**Issue by stilicrafter** [devnied/EMV-NFC-Paycard-Enrollment#48]
Hi,
i bought the old PRO version.
I now switched to the new Samsung Galaxy S10+, but sadly the app show me the message, i should buy the App again.

Google Play seems to no longer have the app listed.
Can i somehow transfer the old PRO Version without this problem from my old S8+ ?

**Comment by stilicrafter** [comment]
![kauf](https://user-images.githubusercontent.com/22886797/54047252-ddb5d980-41d6-11e9-8315-6a8eb49f3688.jpg)

**Comment by devnied** [comment]
This issue is not related to this library

**Comment by stilicrafter** [comment]
I am sorry, cause your name is in the app i thought you wrote the app.
