### ISSUE TITLE
Unresolved reference import javax.smartcardio.CardChannel

### ISSUE THREAD

**Issue by Z-13** [devnied/EMV-NFC-Paycard-Enrollment#49]
Hi, I've an android project on Kotlin and when I try create Provider how into sample, I haven't import the package:
`import javax.smartcardio.CardChannel`

How fix it?

**Comment by nawif** [comment]
same issue here

**Comment by Z-13** [comment]
@devnied hi! perhaps the classes from the package `javax.smartcardio.*` aren't for android app.
If it's possible, can you get an explanation about this question?

Thx!

**Comment by netmindz** [comment]
That example is for java on the desktop, not Android. You need to use the Android NFC APIs not the PCSC framework
