### ISSUE TITLE
How to run it on android ?

### ISSUE THREAD

**Issue by qntbkk** [devnied/EMV-NFC-Paycard-Enrollment#51]
i got a jar file, but does it support to run on android ?

**Comment by Go2Device** [comment]
This repro is a Android Source Project written in Java. Use Android Studio to compile it as a  apk.
I recommend you first, to try some easier projects for the beginning.

**Comment by devnied** [comment]
For Android you just need to use the library:
```
<dependency>
  <groupId>com.github.devnied.emvnfccard</groupId>
  <artifactId>library</artifactId>
  <version>xxx</version>
</dependency>
```
The PcscProvider is only for desktop applications. I have added a provider sample for Android
