### ISSUE TITLE
How can I connect the reader via USB?

### ISSUE THREAD

**Issue by JhonCB** [devnied/EMV-NFC-Paycard-Enrollment#52]
I have an AMR220-C reader and I want to communicate with this library and I did not achieve much, I am using Android Studio.

**Comment by rozzalia** [comment]
U ficxed the prob ?

**Comment by devnied** [comment]
To do that, you need to implement a custom provider with the SDK of your external reader.
For Android you just need to use the library:
```
<dependency>
  <groupId>com.github.devnied.emvnfccard</groupId>
  <artifactId>library</artifactId>
  <version>xxx</version>
</dependency>
```
The PcscProvider is only for desktop applications. I have added a provider sample for Android
