### ISSUE TITLE
Android error: Cannot resolve symbol 'CardChannel' 

### ISSUE THREAD

**Issue by klacus** [devnied/EMV-NFC-Paycard-Enrollment#53]
When I try to follow the IProvider sample in Android Studio (3.5.2, JRE 1.8.0_202, JVM OpenJDK, on Linux), the following error messages appear:
_Cannot resolve symbol 'CardChannel'_

It cannot find smartcardio. The _import.smartcardio_ fails with message: "_Cannot resolve symbol 'smartcardio'_ "

Am I missing a dependency other than the "implementation 'com.github.devnied.emvnfccard:library:3.0.0' ?" 

Android does not seem to have javax.smartcardio. How did you solve it in the sample app on Google Play?

The sample application from Google Play works, but I stuck with these error messages when trying to follow the samples and use the library. I really like how this library is build, but could not figure out how to use it in my project. Spinning around this for 2 weeks now. Any help is appreciated!

**Comment by RiusmaX** [comment]
Same problem here !
Did you find any solution ?

**Comment by mariarodriguer** [comment]
This sample is implemented in Java. In Android you have to use NFC Tag Reader

**Comment by devnied** [comment]
For Android you just need to use the library:
```
<dependency>
  <groupId>com.github.devnied.emvnfccard</groupId>
  <artifactId>library</artifactId>
  <version>xxx</version>
</dependency>
```
The PcscProvider is only for desktop applications. I have added a provider sample for Android
