### ISSUE TITLE
Example for IProvider Android implementation

### ISSUE THREAD

**Issue by RiusmaX** [devnied/EMV-NFC-Paycard-Enrollment#55]
Hi,

Thanks for your work !

Can you provide an example to use this lib with Android ?

I just need an example provider to replace javax.smartcardio.* with an android.nfc.* class (like your app).

I've tried so many things but no results for now :/

Thanks :)

**Comment by DarrelAeturnum** [comment]
Hi. I am having the same issue. Have you found any samples on Android ?

**Comment by RiusmaX** [comment]
Hi ! Yes, Check this out : https://github.com/pro100svitlo/Credit-Card-NFC-Reader

**Comment by DarrelAeturnum** [comment]
> Hi ! Yes, Check this fork : https://github.com/pro100svitlo/Credit-Card-NFC-Reader

Awesome. You're a star ! Thanks @RiusmaX

**Comment by devnied** [comment]
I have added an Android sample for the provider https://github.com/devnied/EMV-NFC-Paycard-Enrollment#android-usage
