### ISSUE TITLE
sample-pcsc with NFC USB reader cound not get anything

### ISSUE THREAD

**Issue by yoldar** [devnied/EMV-NFC-Paycard-Enrollment#6]
Hi! When I try to read card number with PC/SC card in ACS ACR1281 1S Dual Reader there is only responces with "resp: File not found". What I am missing?

INFO [main] (Main.java:29) - Terminals: [PC/SC terminal ACS ACR1281 1S Dual Reader 00 00, PC/SC terminal ACS ACR1281 1S Dual Reader 00 01, PC/SC terminal ACS ACR1281 1S Dual Reader 00 02]
 INFO [main] (Main.java:37) - card: PC/SC card in ACS ACR1281 1S Dual Reader 00 01, protocol T=1, state OK
DEBUG [main] (EmvParser.java:219) - Try to read card with Payment System Environment
DEBUG [main] (EmvParser.java:133) - Select PSE Application
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 0E 31 50 41 59 2E 53 59 53 2E 44 44 46 30 31 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:241) - PSE not found -> Use kown AID
DEBUG [main] (EmvParser.java:274) - Try to read card with AID
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 03
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 03 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 03 10 10
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 00 03 10 10 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 98 08 48
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 00 98 08 48 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 04
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 04 00
DEBUG [main] (PcscProvider.java:61) - resp: 6F 65 84 08 A0 00 00 00 04 00 00 00 A5 59 73 4A 06 07 2A 86 48 86 FC 6B 01 60 0C 06 0A 2A 86 48 86 FC 6B 02 02 01 01 63 09 06 07 2A 86 48 86 FC 6B 03 64 0B 06 09 2A 86 48 86 FC 6B 04 02 55 65 0B 06 09 2B 85 10 86 48 64 02 01 03 66 0C 06 0A 2B 06 01 04 01 2A 02 6E 01 02 9F 6E 06 19 81 01 04 01 00 9F 65 01 FF 90 00
DEBUG [main] (PcscProvider.java:63) - resp: 
6F 65 -- File Control Information (FCI) Template
      84 08 -- Dedicated File (DF) Name
            A0 00 00 00 04 00 00 00 (BINARY)
      A5 59 -- File Control Information (FCI) Proprietary Template
            73 4A -- Directory Discretionary Template
                  06 07 -- Object Identifier (OID)
                        2A 86 48 86 FC 6B 01 (BINARY)
                  60 0C -- [UNKNOWN TAG]
                        06 0A -- Object Identifier (OID)
                              2A 86 48 86 FC 6B 02 02 01 01 (BINARY)
                  63 09 -- [UNKNOWN TAG]
                        06 07 -- Object Identifier (OID)
                              2A 86 48 86 FC 6B 03 (BINARY)
                  64 0B -- [UNKNOWN TAG]
                        06 09 -- Object Identifier (OID)
                              2A 86 48 86 FC 6B 04 02 55 (BINARY)
                  65 0B -- [UNKNOWN TAG]
                        06 09 -- Object Identifier (OID)
                              2B 85 10 86 48 64 02 01 03 (BINARY)
                  66 0C -- [UNKNOWN TAG]
                        06 0A -- Object Identifier (OID)
                              2B 06 01 04 01 2A 02 6E 01 02 (BINARY)
            9F 6E 06 -- Visa Low-Value Payment (VLP) Issuer Authorisation Code
                     19 81 01 04 01 00 (BINARY)
            9F 65 01 -- Track 2 bit map for CVC3
                     FF (BINARY)
90 00 -- Command successfully executed (OK)
DEBUG [main] (PcscProvider.java:66) - resp: Command successfully executed (OK)
DEBUG [main] (ResponseUtils.java:63) - Response Status <9000> : Command successfully executed (OK)
DEBUG [main] (PcscProvider.java:50) - send: 80 A8 00 00 02 83 00 00
DEBUG [main] (PcscProvider.java:61) - resp: 6D 00
DEBUG [main] (PcscProvider.java:63) - resp: 
6D 00 -- Instruction code not supported or invalid
DEBUG [main] (PcscProvider.java:66) - resp: Instruction code not supported or invalid
DEBUG [main] (ResponseUtils.java:63) - Response Status <6D00> : Instruction code not supported or invalid
DEBUG [main] (PcscProvider.java:50) - send: 80 A8 00 00 02 83 00 00
DEBUG [main] (PcscProvider.java:61) - resp: 6D 00
DEBUG [main] (PcscProvider.java:63) - resp: 
6D 00 -- Instruction code not supported or invalid
DEBUG [main] (PcscProvider.java:66) - resp: Instruction code not supported or invalid
DEBUG [main] (ResponseUtils.java:63) - Response Status <6D00> : Instruction code not supported or invalid
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 05
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 05 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 25
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 25 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 42
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 42 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 29
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 29 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 65
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 00 65 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 01 21 10 10
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 01 21 10 10 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 01 41 00 01
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 01 41 00 01 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 01 52 30 10
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 01 52 30 10 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 01 54
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 01 54 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 02 28
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 02 28 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 02 77
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 02 77 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 03 24
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 03 24 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 03 33
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 03 33 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 03 59
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 03 59 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 03 71
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 03 71 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 04 39
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 04 39 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 05 24 10 10
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 05 24 10 10 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 04 32 00 01
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 04 32 00 01 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: D2 76 00 00 25 45 50 01 00
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 09 D2 76 00 00 25 45 50 01 00 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: D5 78 00 00 02 10 10
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 D5 78 00 00 02 10 10 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: F0 00 00 00 03 00 01
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 F0 00 00 00 03 00 01 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 00 24 01
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 06 A0 00 00 00 24 01 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 01 21 10 10
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 01 21 10 10 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 04 54
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 05 A0 00 00 04 54 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 04 76 6C
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 06 A0 00 00 04 76 6C 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
DEBUG [main] (EmvParser.java:296) - Select AID: A0 00 00 03 71 00 01
DEBUG [main] (PcscProvider.java:50) - send: 00 A4 04 00 07 A0 00 00 03 71 00 01 00
DEBUG [main] (PcscProvider.java:61) - resp: 6A 82
DEBUG [main] (PcscProvider.java:63) - resp: 
6A 82 -- File not found
DEBUG [main] (PcscProvider.java:66) - resp: File not found
DEBUG [main] (ResponseUtils.java:63) - Response Status <6A82> : File not found
 INFO [main] (Main.java:43) - card number: null

**Comment by yoldar** [comment]
Sorry, I missed boolean EmvParser(provider, true) :)

**Comment by fozyerr** [comment]
@yoldar Hi this is really really late i know but i am stuck with the ACR 1252 NFC reader right now, i am trying to read credit card info but i am getting same "6A 82 -- File not found" error. I know you probably solved your problem with an older version of this lib but can you help me how to solve this problem. There is no "boolean EmvParser(provider, true)" right now so i can't try your solution. I would be grateful for any kind of help

**Comment by fozyerr** [comment]
> > [@yoldar](https://github.com/yoldar) Hi this is really really late i know but i am stuck with the ACR 1252 NFC reader right now, i am trying to read credit card info but i am getting same "6A 82 -- File not found" error. I know you probably solved your problem with an older version of this lib but can you help me how to solve this problem. There is no "boolean EmvParser(provider, true)" right now so i can't try your solution. I would be grateful for any kind of help
> 
> Hi [@fozyerr](https://github.com/fozyerr)! It was long long time ago. Use ChatGPT to solve problem =)

Wow i am really grateful for your reallly quick answer, after all those years you are still active here :) I will try ChatGPT then, lets see if i can solve it :)
