### ISSUE TITLE
Is there any privacy policy of this library?

### ISSUE THREAD

**Issue by Sp4Rx** [devnied/EMV-NFC-Paycard-Enrollment#73]
This is not a bug. Just curious.

What's the guaranty this library is not coping credit card details to a remote server?

**Comment by devnied** [comment]
This library is provided

**Comment by devnied** [comment]
This library is provided under the terms of the Apache license.

It does not provide a "service" and therefore does not need a privacy policy.

And the best privacy policy you can have with open source software is to read the source code 😉.
